In [ ]:
import numpy as np

print(type(np))

The line import numpy as np is a common statement used in Python to import the NumPy library and assign it the alias np. Here’s a breakdown of what this line does:

Import Statement: import numpy: This instructs Python to load the NumPy library into your current environment. NumPy is a powerful numerical computing library in Python, widely used for array computations and mathematical operations.

Alias Assignment: as np: This part of the statement assigns an alias np to NumPy. This alias allows you to refer to NumPy functions and objects using np instead of typing out numpy each time, which can make your code more concise and readable.

Why Use NumPy?
Efficient Arrays: NumPy provides an array object that is more efficient than Python's built-in list for numerical operations.
Mathematical Functions: NumPy includes a wide range of mathematical functions for operations on these arrays.
Linear Algebra Operations: NumPy supports linear algebra operations, Fourier transforms, and random number generation.

NumPy (Numerical Python) is a fundamental library in Python for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. Here are several reasons why NumPy is widely used and essential in the Python ecosystem:

### 1. **Efficient Array Operations:**
   - NumPy arrays are more efficient than Python lists for numerical operations. They are implemented in C and allow for vectorized operations, where operations are applied to whole arrays instead of individual elements. This reduces the need for explicit loops in Python, making code execution faster and more concise.

### 2. **Multi-dimensional Data Representation:**
   - NumPy arrays can represent multi-dimensional data (e.g., matrices or tensors) with ease. This makes NumPy suitable for handling datasets used in fields such as machine learning, scientific computing, and data analysis.

### 3. **Broad Range of Mathematical Functions:**
   - NumPy provides a rich collection of mathematical functions that operate on arrays. These include basic arithmetic operations, trigonometric functions, statistical functions, linear algebra routines, Fourier transforms, and more. These functions are optimized for performance and provide consistent results across different platforms.

### 4. **Integration with Other Libraries:**
   - NumPy is a foundational library in the Python scientific computing stack. It integrates well with other libraries like SciPy (Scientific Python) for advanced mathematical functions, Matplotlib for plotting, Pandas for data manipulation and analysis, and scikit-learn for machine learning tasks.

### 5. **Memory Efficiency:**
   - NumPy arrays are memory efficient compared to Python lists. They allow for better memory management and enable faster access and manipulation of data. This is crucial when working with large datasets that cannot fit into the computer's main memory.

### 6. **Support for Broadcasting:**
   - Broadcasting is a powerful feature in NumPy that allows operations to be performed on arrays of different shapes. NumPy automatically broadcasts these operations, making code more readable and reducing the need for explicit looping constructs.

### 7. **Platform for Scientific Computing:**
   - NumPy forms the basis for many scientific and numerical computing libraries in Python. Its consistent interface and robust functionality make it a preferred choice for researchers, engineers, and data scientists working on computational and data-intensive applications.

### Example Usage:
```python
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Perform operations
mean_value = np.mean(arr)
print("Mean:", mean_value)
```

In this example:
- `np.array([1, 2, 3, 4, 5])` creates a NumPy array.
- `np.mean(arr)` calculates the mean of the array `arr` using a NumPy function.

### Conclusion:
NumPy's versatility, performance, and extensive mathematical functions make it indispensable for numerical computations and data manipulation in Python. Its efficient handling of arrays, integration with other libraries, and support for advanced operations ensure that it remains a cornerstone of scientific computing and data analysis workflows in Python.

```python
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Perform a mathematical operation (example: square each element)
squared_arr = np.square(arr)

print(squared_arr)



```
In this example:

np.array([1, 2, 3, 4, 5]) creates a NumPy array.
np.square(arr) computes the square of each element in the array using NumPy's vectorized operations.

In [ ]:
arr= np.array([25,41,63,66,85,74])
arr

In [ ]:
type(arr)
#ndarray ==>n dimensiional array

In [ ]:
arr.size #no.of item

In [ ]:
len(arr)

In [ ]:
arr.ndim # to check the dimension of array

In [ ]:
arr= np.array([25,41,63,66,85,74,25.01,"upflairs",True])
arr

In [ ]:
arr.dtype


In [ ]:
np.__version__


The expression np.__version__ is used to retrieve the version number of the NumPy library that is currently imported into your Python environment. Here’s what it does:

np: This refers to the alias np that you assigned to the NumPy library when you imported it using import numpy as np.
.__version__: This is a special attribute of the NumPy module that holds the version information of the library.

In [ ]:
arr= np.array([25,41,63,66,85,74])
arr

In [ ]:
arr[-1]=500
arr[2:4]
arr[::]# start=0,stoping =end,jump==1

In [ ]:
arr*2

In [ ]:
arr[-2]


In [ ]:
arr[::]# start=0,stoping =end,jump==1


# 2D  ARRAYs


In [ ]:
ls=[[1,2,3],
    [4,5,6],
    [7,8,9]]

In [ ]:
arr2 =np.array(ls)
print(arr2)

In [ ]:
type(ls)

In [ ]:
arr2.ndim

In [ ]:
# arr2[0]# for single row only
arr2[0:2]#start to end for more than one row

In [ ]:

# arr2[row,column]=>[row start:stop,col start:end]
arr2[1,1:]

In [ ]:
# arr2[1:3,1:]
arr2[-2:,-2:]

In [ ]:
arr2[-1:-1]=90

### filter all those items that are less than equals to 100
### comments --> how many item in your arrays

In [ ]:
arr= np.random.randint(1,200,500)
arr[arr<=100]

In [ ]:
# for item in arr:
#     count=0
#     if item<=100:
#         count+=1
# print(count)        

In [ ]:
len(arr[arr<=100])

In [ ]:
# arr.shape(3,3)

In [ ]:
arr2=np.random.randint(1,200,(10,5))#range 1 to 200 
# and the rows =10 and columns =5
arr2

In [ ]:
arr=np.zeros((10,5))
arr

In [ ]:
arr.dtype

In [ ]:
arr =np.ones((10,5))
arr

In [ ]:
ls=[0,1,2,3,4,5,6,7,8,9]
ls

In [ ]:
ls=list(range(10))
ls

In [ ]:
arr=np.arange(20)
arr# always create single dimension array in sorted manner from 0 to 20/range we have given

In [ ]:
arr=np.arange(60)
arr

In [ ]:
arr.reshape(10,6)#10(rows)*6(columns)==60
# arr.reshape(10,7)#this will show error because 10*7==70 which is invalis=d as it exceed the range of it

In [ ]:
arr.reshape(30,2)


The reshape method in NumPy is used to change the shape (dimensions) of an array without changing its data. Here’s a detailed explanation of how arr.reshape works and its usage:

Syntax and Parameters
The reshape method in NumPy typically takes one or more arguments:

```python

arr.reshape(shape, order='C')
```
arr: This is the NumPy array that you want to reshape.
shape: This parameter specifies the new shape that you want the array to have. It can be specified in several formats:
A single integer, which means the resulting array will have that many dimensions.
A tuple of integers, where each integer specifies the size of the corresponding dimension in the reshaped array. The total number of elements in the reshaped array must match the original array.
order: This is an optional parameter that specifies the order of the elements in the reshaped array. It can be 'C' (row-major, C-style) or 'F' (column-major, Fortran-style).
How reshape Works
Shape Compatibility: The total number of elements in the original array (arr) must be equal to the total number of elements in the reshaped array specified by shape. NumPy will raise an error if these numbers do not match.

Data View: reshape does not copy the data; it returns a new view of the original array with the specified shape. This means that modifying the reshaped array will also modify the original array.

# CREATION OF 3D ARRAY


In [ ]:
arr1=[1,2,3] # 1d array
arr2=[[1,2,3],[1,2,3],[1,2,3]] #2d array
arr3 = [
    [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
    [[1, 2, 3], [1, 2, 3], [1, 2, 3]]
]#3d array

In [24]:
import numpy as np

In [25]:
arr3=np.random.randint(1,200,(3,5,3))
arr3

array([[[181, 199, 168],
        [139, 140, 126],
        [141, 135,  52],
        [ 17, 106,  45],
        [ 56, 194,  81]],

       [[ 82,  22, 176],
        [136, 144,  18],
        [131,  99, 173],
        [132,  26,  61],
        [169,   5, 136]],

       [[130,  66, 142],
        [ 81,  23,  47],
        [ 44,  33, 189],
        [128, 110, 154],
        [ 83, 163,  28]]], dtype=int32)

In [ ]:
arr3.ndim

In [ ]:
arr3.dtype

In [ ]:
arr3.shape

### how to access the value from the array 
*arr[table,row,column]<- indexing method

In [ ]:
arr3[1,4,0:]

In [ ]:
arr3[2,0:2,1:3]

In [ ]:
# arr3[0,0:1,0:]
arr3[-2,-5:-4,-5:]

In [ ]:
arr3[-1,-5:-4,-5:]

# OTHER FUNCTIONS IN NUMPY AND THEIR FUNCTIONALITY

In [26]:
arr=np.array([9,7,8])
arr

array([9, 7, 8])

In [27]:
max(arr)

np.int64(9)

In [28]:
min(arr)

np.int64(7)

In [29]:
np.mean(arr)# average of the array

np.float64(8.0)

In [30]:
np.sum(arr)

np.int64(24)

In [31]:
np.argmin(arr)# this show the the index of the minimum number


np.int64(1)

In [34]:
np.argmax(arr)# this shows the index of the maximum item in array 

np.int64(0)

In [37]:
arr.sort()
arr

array([7, 8, 9])

In [38]:
arr[::-1]#descending order

array([9, 8, 7])

# try with 4D  and 5-D array homework